import type { Metadata } from "next";
import { Geist, Geist_Mono, Oswald } from "next/font/google";
import "./globals.css";
import { cx } from "class-variance-authority";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const oswald = Oswald({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cx("dark")}>
      <body
        className={cx(`${geistSans.variable} ${geistMono.variable} antialiased`, "flex flex-col min-h-screen")}
        // className={cx(`${ oswald.className } antialiased`, "flex flex-col min-h-screen")}
      >
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
